### ISSUE TITLE
installing in the user home dir

### ISSUE THREAD

**Issue by eadmaster** [yahoo/redislite#106]
I've tried installing in the user home dir with:

```
$ easy_install --user redislite
Searching for redislite
Reading https://pypi.python.org/simple/redislite/
Best match: redislite 3.0.296
Downloading https://pypi.python.org/packages/6a/88/9e51c7b7b2891952b2c79215a5e0ab16df7407c02e8708c39f010a1cda4d/redislite-3.0.296.tar.gz#md5=359ad42d38fafbf7cd9684d66ad114fc
Processing redislite-3.0.296.tar.gz
Writing /tmp/easy_install-df_96j/redislite-3.0.296/setup.cfg
Running redislite-3.0.296/setup.py -q bdist_egg --dist-dir /tmp/easy_install-df_96j/redislite-3.0.296/egg-dist-tmp-69ZJ02
warning: no files found matching 'README.md'
warning: no files found matching '*' under directory 'redislite/bin'
warning: no previously-included files found matching '*dummy.o'
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

zip_safe flag not set; analyzing archive contents...
Adding redislite 3.0.296 to easy-install.pth file

Installed /root/.local/lib/python2.7/site-packages/redislite-3.0.296-py2.7-linux-i686.egg
Processing dependencies for redislite
Searching for redis
Reading https://pypi.python.org/simple/redis/
Best match: redis 2.10.5
Downloading https://pypi.python.org/packages/68/44/5efe9e98ad83ef5b742ce62a15bea609ed5a0d1caf35b79257ddb324031a/redis-2.10.5.tar.gz#md5=3b26c2b9703b4b56b30a1ad508e31083
Processing redis-2.10.5.tar.gz
Writing /tmp/easy_install-bh7CA6/redis-2.10.5/setup.cfg
Running redis-2.10.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bh7CA6/redis-2.10.5/egg-dist-tmp-IPnQzc
warning: no previously-included files found matching '__pycache__'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: build_py: byte-compiling is disabled, skipping.

warning: install_lib: byte-compiling is disabled, skipping.

zip_safe flag not set; analyzing archive contents...
Adding redis 2.10.5 to easy-install.pth file

Installed /root/.local/lib/python2.7/site-packages/redis-2.10.5-py2.7.egg
Finished processing dependencies for redislite

```
The module seems to install fine, but no redis-server binary is built.
Also, when i try to create a new Redis istance it fails:

```
Python 2.7.6 (default, Mar 22 2014, 22:59:38)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from redislite import Redis
>>> redis_connection = Redis('/tmp/redis.db')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/lib/python2.7/site-packages/redislite-3.0.296-py2.7-linux-i686.egg/redislite/client.py", line 386, in __init__
  File "/root/.local/lib/python2.7/site-packages/redislite-3.0.296-py2.7-linux-i686.egg/redislite/client.py", line 178, in _start_redis
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Can i run redislite without the server binary?

**Comment by dwighthubbard** [comment]
redislite won't run if it doesn't generate the server binary.  After looking into this, it appears this is happening when using easy_install but works properly when using pip.

I have updated the documentation to remove references to using easy_install to install the package.

**Comment by eadmaster** [comment]
allright, i've switched to [mockredis](https://github.com/locationlabs/mockredis) for a server-less alternative.
